const animalObjects= [{
    "imageUrl":"./assets/fox.png",
    "imageText":"fox"
  },{
    "imageUrl":"./assets/bear.png",
    "imageText":"bear"
  },{
    "imageUrl":"./assets/lion.png",
    "imageText":"lion"
  },{
    "imageUrl":"./assets/snake.png",
    "imageText":"snake"
  },{
    "imageUrl":"./assets/rat.png",
    "imageText":"rat"
  },{
    "imageUrl":"./assets/owl.png",
    "imageText":"owl"
  },{
    "imageUrl":"./assets/chicken.png",
    "imageText":"chicken"
  },{
    "imageUrl":"./assets/hippo.png",
    "imageText":"hippo"
  },{
    "imageUrl":"./assets/fox.png",
    "imageText":"fox"
  },{
    "imageUrl":"./assets/bear.png",
    "imageText":"bear"
  },{
    "imageUrl":"./assets/lion.png",
    "imageText":"lion"
  },{
    "imageUrl":"./assets/snake.png",
    "imageText":"snake"
  },{
    "imageUrl":"./assets/rat.png",
    "imageText":"rat"
  },{
    "imageUrl":"./assets/owl.png",
    "imageText":"owl"
  },{
    "imageUrl":"./assets/chicken.png",
    "imageText":"chicken"
  },{
    "imageUrl":"./assets/hippo.png",
    "imageText":"hippo"
  }]